# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aphrodite' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'AVOSCloud'                  # 数据存储、短信、云引擎调用等基础服务模块
   pod 'AVOSCloudIM'                # 实时通信模块
   pod 'AVOSCloudCrashReporting'    # 错误报告模块
   pod 'MJRefresh' 
   pod ‘SDWebImage’

  # Pods for Aphrodite

  target 'AphroditeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AphroditeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
